# Generated by Django 3.2 on 2021-04-19 00:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(verbose_name='Manzil ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email manzil ')),
                ('contact_num', models.CharField(max_length=32, verbose_name='Kontakt raqam ')),
                ('twitter',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter linki (shart emas) ')),
                ('facebook',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook linki (shart emas) ')),
                ('instagram',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram linki (shart emas) ')),
                ('skype',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Skype linki (shart emas) ')),
                ('linkedin_box', models.CharField(blank=True, max_length=200, null=True,
                                                  verbose_name='linkedin-box linki (shart emas) ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontakt',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ismi ')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Telefon raqami ')),
                ('message', models.TextField(max_length=1500, verbose_name='Habari ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Habarlar',
                'verbose_name_plural': 'Habarlar',
            },
        ),
        migrations.CreateModel(
            name='GalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Rasmlar', verbose_name='Foto rasmi ')),
                ('main_title', models.CharField(max_length=32, verbose_name='Gallereya nomi ')),
                ('title', models.CharField(blank=True, max_length=32, null=True, verbose_name="Gallereya ma'lumoti ")),
                ('message', models.TextField(blank=True, null=True, verbose_name='Gallereya habari ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Gallereya',
                'verbose_name_plural': 'Gallereya',
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Yangiliklar', verbose_name='Foto rasmi ')),
                ('title', models.CharField(max_length=45, verbose_name='Yangiliklar nomi ')),
                ('message', models.TextField(verbose_name='Yangiliklardagi habar ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=64, verbose_name='Ismi ')),
                ('photo', models.ImageField(help_text="O'lcahmi 3x4 bo'lgan rasmni kiriting!", upload_to='Hodimlar',
                                            validators=[main.models.staff_photo_dimensions],
                                            verbose_name='Foto rasmi ')),
                ('title', models.CharField(max_length=64, verbose_name='Vazifasi ')),
                ('info', models.TextField(blank=True, null=True, verbose_name="Ma'lumot ")),
                ('twitter',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter linki (shart emas) ')),
                ('facebook',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook linki (shart emas) ')),
                ('instagram',
                 models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram linki (shart emas) ')),
                ('linkedin_box', models.CharField(blank=True, max_length=200, null=True,
                                                  verbose_name='linkedin-box linki (shart emas) ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Hodimlar',
                'verbose_name_plural': 'Hodimlar',
            },
        ),
        migrations.CreateModel(
            name='ThisIsBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=48, null=True, verbose_name='Bannerning nomi ')),
                ('message_on_title',
                 models.TextField(blank=True, max_length=216, null=True, verbose_name="Bannerdagi ma'lumot ")),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name="O'zgartirilgan vaqti")),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
