# Generated by Django 3.2 on 2021-04-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thisisbannermodel',
            old_name='message_on_title',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='thisisbannermodel',
            old_name='main_title',
            new_name='title',
        ),
    ]
