# Generated by Django 3.2 on 2021-04-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210419_0544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThisIsBannerModel',
            new_name='BannerModel',
        ),
    ]
