# Generated by Django 3.2 on 2021-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_thisisbannermodel_bannermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='location',
            field=models.TextField(verbose_name='Manzil (address) '),
        ),
    ]
