# Generated by Django 3.2 on 2021-04-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contactmodel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook linki (shart emas) '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram linki (shart emas) '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='linkedin_box',
            field=models.URLField(blank=True, null=True, verbose_name='linkedin-box linki (shart emas) '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='skype',
            field=models.URLField(blank=True, null=True, verbose_name='Skype linki (shart emas) '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter linki (shart emas) '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Kiritilgan vaqti'),
        ),
    ]
