# Generated by Django 6.0.3 on 2026-03-06 00:16

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210421_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermodel',
            name='message',
            field=models.TextField(blank=True, help_text="Bannerdagi ma'lumot mavjud bo'lmasa bo'sh qoldiring", max_length=216, null=True, verbose_name="Bannerdagi ma'lumot "),
        ),
        migrations.AlterField(
            model_name='bannermodel',
            name='title',
            field=models.CharField(help_text='Bannerdagi mavzu yoki uning nomi', max_length=48, null=True, verbose_name='Bannerning nomi '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='contact_num',
            field=models.CharField(help_text="Bog'chaning kontakt raqami (Aloqaga kirib bo'ladigan raqam)", max_length=32, verbose_name='Kontakt raqam '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(help_text="Bog'chaning emaili", max_length=254, verbose_name='Email manzil '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='facebook',
            field=models.URLField(blank=True, help_text="Bog'chaning facebookdagi gruppaning linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='Facebook linki '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='instagram',
            field=models.URLField(blank=True, help_text="Bog'chaning instagramdagi gruppaning linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='Instagram linki '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='linkedin_box',
            field=models.URLField(blank=True, help_text="Bog'chaning linkedin_box dagi gruppaning linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='linkedin-box linki '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='location',
            field=models.TextField(help_text="Bog'chaning manzili", verbose_name='Manzil (address) '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='skype',
            field=models.URLField(blank=True, help_text="Bog'chaning skype dagi gruppaning linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='Skype linki '),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='twitter',
            field=models.URLField(blank=True, help_text="Bog'chaning twitterdagi gruppaning linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='Twitter linki '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='message',
            field=models.TextField(help_text="Habar yuboruvchining habari (yuborgan ma'lumoti)", max_length=1500, verbose_name='Habari '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Habar yuboruvchining ismi', max_length=120, verbose_name='Ismi '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text='Habar yuboruvchining telefon raqami', max_length=13, verbose_name='Telefon raqami '),
        ),
        migrations.AlterField(
            model_name='galarymodel',
            name='main_title',
            field=models.CharField(help_text='Gallereyadagi assosiy mavzuning nomi', max_length=32, verbose_name='Gallereya nomi '),
        ),
        migrations.AlterField(
            model_name='galarymodel',
            name='message',
            field=models.TextField(blank=True, help_text="Gallereyadagi habarlar (Gallereyada ma'lumotni yozmasez, bo'sh qoldiring)", null=True, verbose_name='Gallereya habari '),
        ),
        migrations.AlterField(
            model_name='galarymodel',
            name='photo',
            field=models.ImageField(help_text="Gallereyadagi rasm (Bolalar rasmi, Bog'chaning rasmi ...)", upload_to='Rasmlar', verbose_name='Foto rasmi '),
        ),
        migrations.AlterField(
            model_name='galarymodel',
            name='title',
            field=models.CharField(blank=True, help_text="Gallereydagi ma'lumot (Gallereyadagi mavzu lekin assosiysi emas)", max_length=32, null=True, verbose_name="Gallereya ma'lumoti "),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='image',
            field=models.ImageField(help_text='Yangiliklardagi rasm', upload_to='Yangiliklar', verbose_name='Foto rasmi '),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='message',
            field=models.TextField(help_text="Yangilikdagi o'zgarishlardagi habarlar", verbose_name='Yangiliklardagi habar '),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='title',
            field=models.CharField(help_text='Yangilikdagi mavzuning nomi', max_length=45, verbose_name='Yangiliklar nomi '),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='facebook',
            field=models.URLField(blank=True, help_text="Hodimning facebookdagi profilidagi linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='Facebook linki '),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='info',
            field=models.TextField(blank=True, help_text="Hodim haqida ma'lumot yoki habar", null=True, verbose_name="Ma'lumot "),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='instagram',
            field=models.URLField(blank=True, help_text="Hodimning instagramdagi profilidagi linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='Instagram linki '),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='linkedin_box',
            field=models.URLField(blank=True, help_text="Hodimning linkedin_box profilidagi linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='linkedin-box linki '),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='main_title',
            field=models.CharField(help_text='Hodimning ismi', max_length=64, verbose_name='Ismi '),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='photo',
            field=models.ImageField(help_text="Hodimning foto rasmi (o'lcahmi 3x4 nisbatda bo'lgan rasmni kiriting)", upload_to='Hodimlar', validators=[main.models.staff_photo_dimensions], verbose_name='Foto rasmi '),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='title',
            field=models.CharField(help_text='Hodimning vazifasi', max_length=64, verbose_name='Vazifasi '),
        ),
        migrations.AlterField(
            model_name='staffmodel',
            name='twitter',
            field=models.URLField(blank=True, help_text="Hodimning twitterdagi profilidagi linki mavjud bo'lmasa bo'sh qoldiring", null=True, verbose_name='Twitter linki '),
        ),
    ]
